#!/bin/bash

set -ex

if [ "x$CIP_ENV" == "x" ]; then
  echo "please set CIP_ENV to one of:"
  echo " export CIP_ENV=ALIEN_INSTALL_TYPE=share"
  echo " export CIP_ENV=ALIEN_INSTALL_TYPE=system"
  false
fi

cip sudo apt-get update

if echo $CIP_ENV | grep -q system; then

  cip sudo apt-get -y install libffi-dev
  cip pkg ab/lucet-runtime

else

  cip sudo apt-get -y install git libffi-dev
  cip pkg rust

fi

cip exec cpanm -n FFI::Platypus
